import 'package:dart_openai/dart_openai.dart';

class OpenAIController {

  List<OpenAIChatCompletionChoiceMessageModel> messages = [];

  resetMessages() => messages = [];


  /// The “system” role typically provides high-level instructions
  /// It helps guide the behavior of the assistant throughout the conversation.
  /// For example, a system message could be “You are a helpful assistant.”,
  /// Or, "return any message you are given as JSON.".
  addSystemGuide(String input){
    messages.add(
        OpenAIChatCompletionChoiceMessageModel(
          content: [
            OpenAIChatCompletionChoiceMessageContentItemModel.text(input),
          ],
          role: OpenAIChatMessageRole.system,
        ));
  }

  /// The “user” role represents the messages from the end-user interacting with the model.
  /// For instance, a user message could be “Tell me a fun fact.”
  addUserMessage(String input){
    messages.add(
        OpenAIChatCompletionChoiceMessageModel(
          content: [
            OpenAIChatCompletionChoiceMessageContentItemModel.text(input),
          ],
          role: OpenAIChatMessageRole.user,
        ));
  }

  /// The “assistant” role represents the responses generated by the ChatGPT model.
  addAssistantResponse(String input){
    messages.add(
        OpenAIChatCompletionChoiceMessageModel(
          content: [
            OpenAIChatCompletionChoiceMessageContentItemModel.text(input),
          ],
          role: OpenAIChatMessageRole.assistant,
        ));
  }

}